print("Вітаю!")
a = int(input('a '))
b = int(input('b '))
c = int(input('c '))
d = int(input('d '))
e = int(input('e '))
print(f'Max={max(a, b, c, d, e)}')
print(f'Min={min(a, b, c, d, e)}')
print(f'Avg={(a + b + c + d + e) / 5}')